# Site Settings
title: Markdown notes site
description: >
  Markdown notes to Jekyll site with Knowledge Graph. 
baseurl: '/md_notes_site'
url: 'https://richardpordan.github.io'
sass:
  sass_dir: _sass
include: ['_notes', '_pages']
