# Site Settings
title: Markdown notes site
description: >
  Markdown notes to Jekyll site with Knowledge Graph. 
baseurl: ''
url: 'https://md_notes_site.pages.dev'
sass:
  sass_dir: _sass
include: ['_notes', '_pages']
