# Site Settings
title: Markdown notes site
description: >
  Markdown notes to Jekyll site with Knowledge Graph. 
baseurl: ''
url: 'http://localhost:4000'
sass:
  sass_dir: _sass
include: ['_notes', '_pages']
